blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Feature Requests & Questions
    url: https://github.com/RanitManik/codesnap/discussions
    about: Please ask and answer questions in the discussions section